services:
  mysql:
    image: mysql:8.1
    container_name: chat-db
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - network
  chat-service:
#    restart: always
    container_name: chat-service
    ports:
      - "${SERVICE_PORT}:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PROFILE_ACTIVE: test
      ROOT_LOG_LEVEL: error
      WEB_LOG_LEVEL: debug
      DB_HOST: mysql:3306
    networks:
      - network
    volumes:
      - logs:/sc-chat/logs
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
volumes:
  db-data:
    name: chat-db
  logs:
    name: chat-logs
networks:
  network:
    name: chat-network